// src/shared/ui/navigation/site-link.svelte
<script lang="ts">
import type { HTMLAnchorAttributes } from "svelte/elements"

interface $$Props {
    label?: string
    target?: HTMLAnchorAttributes["target"]
}

interface $$Slots {
    default: NonNullable<unknown>
}

export let label: string = "game-values.com"

export let target: HTMLAnchorAttributes["target"] = undefined
</script>

<a
    class="link link-primary link-hover"
    href="https://game-values.com"
    {target}
>
    <slot>
        {label}
    </slot>
</a>

// backup/_backup/src/components/app/Sitelink.vue
<script lang="ts" setup>
import type { ScopedProps } from "~/types"
import type { VNode } from "vue"

withDefaults(defineProps<{
    label?: string
    url?: string
}>(), {
    label: "game-values.com",
    url: "https://game-values.com/",
})

defineSlots<{
    default: (scopedProps: ScopedProps) => VNode
}>()
</script>

<template>
<ui-link
    :href="url"
    target="_blank"
    type="primary"
>
    <slot>
        {{ label }}
    </slot>
</ui-link>
</template>
