// src/shared/ui/preview/preview.svelte
<script lang="ts">
import { Image } from "@smui/image-list"

export let alt: string = "preview"

export let src: string
</script>

<div
    class="
        absolute top-0 left-0
        w-full h-full max-h-31.25rem
    "
>
    <div
        class="
            absolute top-0 left-0
            w-full h-32
            bg-gradient-to-b from-black
        "
    />

    <Image
        class="w-full h-full object-cover"
        {alt}
        loading="lazy"
        {src}
    />
</div>

// backup/_backup/src/entities/game/Preview.vue
<script lang="ts" setup>
let { storeClient } = useClients()

let { game } = storeToRefs(storeClient.gameStore)
</script>

<template>
<ui-overlay
    :style="{
        position: 'absolute',
        top: '-7rem',
    }"
    height="500"
>
    <ui-image :src="game.image" />

    <template #overlay>
        <div
            class="
                fit
                bg-gradient-to-b
                from-black
                from-0%
            "
        />
    </template>
</ui-overlay>
</template>
